### ISSUE TITLE
'java.lang.NoSuchMethodError' when launching API tests

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#2016]
'void org.apache.tika.io.IOUtils.closeQuietly(java.io.InputStream)' appears when launching API tests after upgrade from 0.3.7 to 0.3.8 Vividus version, e.g for the step " When I send HTTP POST to the relative URL 'sso/token'"

STR:
Given request body: ｟password=${password}&username=${email}｠ 
When I set request headers:［ |name |value | |Content-Type |application/x-www-form-urlencoded|］ 
When I send HTTP ｟POST｠ to the relative URL 'sso/token'
NOTE: response is successful and contains body, but further steps are not executable.
When I save response body to the SCENARIO,NEXT_BATCHES variable 'sso_token' 
When I save response body to the SCENARIO,NEXT_BATCHES variable 'admin_sso_token' 
Then the response code is equal to '200' 

Error log:
java.lang.NoSuchMethodError: 'void org.apache.tika.io.IOUtils.closeQuietly(java.io.InputStream)'
	at com.epam.reportportal.utils.MimeTypeDetector.detect(MimeTypeDetector.java:65)
	at com.epam.reportportal.message.HashMarkSeparatedMessageParser$MessageType$2.toByteSource(HashMarkSeparatedMessageParser.java:66)
	at com.epam.reportportal.message.HashMarkSeparatedMessageParser.parse(HashMarkSeparatedMessageParser.java:98)
	at com.epam.ta.reportportal.log4j.appender.ReportPortalLog4j2Appender$1.apply(ReportPortalLog4j2Appender.java:116)
	at com.epam.ta.reportportal.log4j.appender.ReportPortalLog4j2Appender$1.apply(ReportPortalLog4j2Appender.java:82)
	at com.epam.reportportal.service.LoggingContext$4.apply(LoggingContext.java:173)
	at com.epam.reportportal.service.LoggingContext$4.apply(LoggingContext.java:170)
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onSuccess(MaybeMap.java:82)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:66)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeMap.subscribeActual(MaybeMap.java:40)
	at io.reactivex.Maybe.subscribe(Maybe.java:4096)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable.subscribeActual(MaybeToFlowable.java:45)
	at io.reactivex.Flowable.subscribe(Flowable.java:14419)
	at io.reactivex.Flowable.subscribe(Flowable.java:14365)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:52)
	at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:309)
	at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:229)
	at com.epam.reportportal.service.LoggingContext.emit(LoggingContext.java:170)
	at com.epam.reportportal.service.ReportPortal.emitLog(ReportPortal.java:147)
	at com.epam.ta.reportportal.log4j.appender.ReportPortalLog4j2Appender.append(ReportPortalLog4j2Appender.java:82)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:540)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:498)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:481)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:456)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:188)
	at org.slf4j.spi.DefaultLoggingEventBuilder.logViaPublicSLF4JLoggerAPI(DefaultLoggingEventBuilder.java:118)
	at org.slf4j.spi.DefaultLoggingEventBuilder.innerLog(DefaultLoggingEventBuilder.java:86)
	at org.slf4j.spi.DefaultLoggingEventBuilder.log(DefaultLoggingEventBuilder.java:56)
	at org.vividus.reportportal.listener.AttachmentListener.onAttachmentPublish(AttachmentListener.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.vividus.reporter.event.AttachmentPublisher.publishAttachment(AttachmentPublisher.java:59)
	at org.vividus.reporter.event.AttachmentPublisher.publishAttachment(AttachmentPublisher.java:43)
	at org.vividus.http.HttpClientInterceptor.attachApiMessage(HttpClientInterceptor.java:105)
	at org.vividus.http.HttpClientInterceptor.handle(HttpClientInterceptor.java:94)
	at org.vividus.http.client.HttpClient.execute(HttpClient.java:114)
	at org.vividus.http.HttpRequestExecutor.executeHttpRequest(HttpRequestExecutor.java:77)
	at org.vividus.bdd.steps.api.HttpRequestSteps.whenIDoHttpRequestToRelativeURL(HttpRequestSteps.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:861)
	at org.jbehave.core.steps.StepCreator$ReportingAbstractStep.perform(StepCreator.java:686)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:387)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1335)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.perform(PerformableTree.java:1214)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:1193)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performScenario(PerformableTree.java:1205)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:1252)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:1108)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:997)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:964)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:471)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:438)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:299)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:272)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Execution environment (please complete the following information):**
 - Vividus version: 0.3.8
 - OS: macOS BigSur 11.5.2]
 - java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

![Screenshot 2021-09-29 at 13 55 38](https://user-images.githubusercontent.com/54664070/135264248-6e08e002-a95e-4b99-a205-81eded317c31.png)
